### ISSUE TITLE
HasField doesn't accept dynamically generated strings

### ISSUE THREAD

**Issue by mikolajz** [dropbox/mypy-protobuf#107]
We started using mypy-protobuf for a bit larger codebase and hit two problems. For the first I have PR https://github.com/dropbox/mypy-protobuf/pull/106, the second is harder.

mypy-protobuf create this nice Literal union to validate the parameter to HasField when it's a literal. However, when it's dynamically generated, it fails the type check (e.g., `foo.HasField(arg + "_timestamp")`). I don't know - is it possible to still validate the literal strings while allowing for non-literal strings as well?

**Comment by nipunn1313** [comment]
Ah interesting

This was done intentionally in #62 

We have a history of being somewhat opinionated in the typing to help ourselves catch issues (see #65)

In this case, we could have the type param for HasField take a `str`, but then it loses the benefit of the `Union[Literal['a_timestamp'], Literal['b_timestamp']]`, which can help find typos/bugs

I can think of a couple options here

1 - update your codebase with something like this - to bypass the strict literals.
```
foo.HasField(cast(Any, arg+"timestamp"))
```

2 - give the proto generator a flag (in `request.parameter`) for `relax_hasfield_literal` which changes it to take a "str" instead of a union of literals

3 - Add a proto message extension which gives the functionality of 2 to specific messages. There is no precedent for this in mypy protobuf, but it could work.


I'd probably lean for (1) just because the benefits of Union are often worthwhile, but I understand that in large codebases, it can be difficult. Really depends on how pervasive this dynamic pattern is. Would be willing to accept either 2 or 3.

**Comment by nipunn1313** [comment]
Also happy to hear that you started using it in a larger codebase! That's where it shines!

**Comment by mikolajz** [comment]
The codebase is larger, but not that large :) and we have so far only 1 case (and will probably have another once we extend the coverage again), so it's easy to add a cast. I agree that if there is no way to accept both strings and a fixed set of literals, it's better the way it's currently done.

**Comment by mikolajz** [comment]
Hi, will you be releasing a new version? I'm again wanting to decide whether we should patch it locally or just wait for a new version.

**Comment by nipunn1313** [comment]
ah sure - I can release
