### ISSUE TITLE
The split enum value types break type checks when used with dataclasses

### ISSUE THREAD

**Issue by sagar-infinitus-ai** [dropbox/mypy-protobuf#126]
Changes made in https://github.com/dropbox/mypy-protobuf/pull/120 are breaking typechecks when compiled types are used with dataclasses, or in general when enums are used as parameters or return values. 

Quick example: 
proto: 
```
syntax = "proto3";

package bikes;
    
enum EngineType {
    TWO_STROKE = 0;
    FOUR_STROKE = 1;
}

message Motorcycle {
    string name = 1;
    EngineType engine_type = 2;
}
```
python: 
```
from dataclasses import dataclass
from motorcycles_pb2 import Engine, EngineType, Motorcycle

@dataclass
class DemoEngine:
    engine_type: EngineType
    name: str

    def __init__(self, engine_type: EngineType, name: str):
        self.engine_type = engine_type
        self.name = name

d = DemoEngine(EngineType.TWO_STROKE, "demo")
```
type check failure: 
```
motorcycles/__main__.py:17: error: Argument 1 to "DemoEngine" has incompatible type "EngineTypeValue"; expected "EngineType"
```
Protos compiled with protoc 3.12.2 using `python -m grpc_tools.protoc`

**Comment by nipunn1313** [comment]
Hi! Sorry for the delay - I've been recovering from a shoulder procedure, but starting to feel well again.

Thanks for the report. I actually believe that the previous behavior of mypy-protobuf was inconsistent with the python generated code (and thus incorrect). With 1.21 (see https://github.com/dropbox/mypy-protobuf/blob/master/CHANGELOG.md) the current behavior is correct.

The type `EngineType` is actually a subclass of `EnumTypeWrapper` (see https://developers.google.com/protocol-buffers/docs/reference/python-generated#enum and https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/enum_type_wrapper.py)

In your example, `EngineType.TWO_STROKE` is not actually of type `EngineType`, but rather of type `int`. `EngineTypeValue` is a wrapper `NewType` around `int` to get stronger typing guarantees, but I believe you could use `int` in your code as well and things would typecheck.

Would be open to suggestions on how to make this more clear. Perhaps I can add more details to the changelog entry for 1.21?

**Comment by nipunn1313** [comment]
This does mean that updating from 1.20 to 1.21 will involve changes to the source code in order to work. The generated enum code in 1.20 and the type annotations in your toy example are incorrect.

In your toy example, it would involve changing to
```
from dataclasses import dataclass
from motorcycles_pb2 import Engine, EngineType, EngineTypeValue, Motorcycle

@dataclass
class DemoEngine:
    engine_type: EngineTypeValue
    name: str

    def __init__(self, engine_type: EngineTypeValue, name: str):
        self.engine_type = engine_type
        self.name = name

d = DemoEngine(EngineType.TWO_STROKE, "demo")
```

On the one hand, it feels reasonable to fix this bug w/ 1.21 to move toward more correct annotations.

On the other hand, I'm empathetic to the challenge of updating code annotations. If there is a big forcing desire, I would consider a flag like `--preserve-buggy-enum-as-enum-value-annotations` which when set would revert to the buggy behavior of treating `EngineType.TWO_STROKE` as an `EngineType` rather than `EngineTypeValue` / `int`. Such a flag would really dirty up the mypy-protobuf source and testing matrix, so I'd only want to consider it if it's a very big pain point. I'd rather spend the energy working on documentation for how to migrate, if that's more viable.

**Comment by nipunn1313** [comment]
I may consider having `EngineTypeValue` available as `EngineType.Value` for scoping.

**Comment by sagar-infinitus-ai** [comment]
Hey! Thanks for the response. Sorry, I think i missed something in my original report. You are right in that `EngineType` is the wrapper class and does not represent the value being returned. So for that, introducing EngineTypeValue makes sense. Making code changes to reflect this is not a big deal.
The problem is that EngineTypeValue is only available in the pyi files and not in the py files - so this will cause a runtime error. 
Changing it to int seems like cheating to me - what if the enum was a mix of types? 
What I'm getting out of this is that there does not seem to be a type (outside of pyi) that represents an enum value? Is that a fair conclusion?

**Comment by nipunn1313** [comment]
yes! You have a couple of options

1 - you can use `int`. That is the type that the generated code uses. You lose some type checking, but it's simple.
2 - You can use `'EngineTypeValue'` as your type using a forward reference (enclosed in a string). https://mypy.readthedocs.io/en/stable/kinds_of_types.html#class-name-forward-references. @pcorpet has had success with this option
3 - You can conditionally import `EngineTypeValue`. A common pattern we've used at DBX is
```
MYPY = False
if MYPY:
   from engine_pb2 import EngineTypeValue
```

In order to truly fix this, we'll have to upstream a `NewType` into the python generated code. It's possible folks over at google will be amenable to this, but haven't brought it up with them.

**Comment by nipunn1313** [comment]
I'm hoping that having value available as `EngineType.Value` may alleviate some of this concern

**Comment by sagar-infinitus-ai** [comment]
Ah.. ok. I understand now. A combination of forward references and the import trick works (ie, mypy succeeds and no runtime errors)... but still fails pylint :)
```
$ pipenv run pylint motorcycles --load-plugins=pylint_protobuf
...
...s/mypy-protobuf-bug-xp7ylla-/lib/python3.7/site-packages/pylint_protobuf/__init__.py", line 601, in import_module_
    new_scope[alias] = new_names[qualified_name(name)]
KeyError: 'motorcycles_pb2.EngineTypeValue
```

(I'm fairly new to python so apologies if I missed obvious solutions). 
For us, until everyone agrees on a good solution, it does seem like we either: (1) freeze our mypy-protobuf to 1.20 (which we're doing right now), or remove type checks around enums (which is not ideal)

**Comment by nipunn1313** [comment]
In #129 - I added some tests which show the various ways you can reference the value!

I was unable to get Forward References to work (pcorpet managed to - so it seems possible, but I don't know how), but I got every other technique to work and there are tests to show.

I also played with having value available as `EngineType.Value`, but it seems very difficult because `EngineType` is actually generated as an instance of the `class _EngineType(EnumWrapperType)`, so mypy won't recognize `EngineType.Value`. There may be a way to hack it to work, but I can't seem to figure it out.

Another option would be to upstream the `EngineTypeValue` type into the google generated code - which we could look into to make this easier.

**Comment by pcorpet** [comment]
@nipunn1313 In your PR you're only using comments for types. As such all you use are strings (they are never considered as actual Python object). What I use is full typing annotations but using strings:

```py
e: 'test_pb2.OuterEnumValue' = test_pb2.BAR
```
Previously I was able to use without the quotes but not anymore
```py
e: test_pb2.OuterEnum = test_pb2.BAR
```

**Comment by nipunn1313** [comment]
Ah. Since it is using py3 syntax, I need to add a test file which only runs
in py3

**Comment by nipunn1313** [comment]
cool - I will close this out and make a task to add a py3-syntax test.
