### ISSUE TITLE
Support for optional proto3 fields

### ISSUE THREAD

**Issue by henribru** [dropbox/mypy-protobuf#146]
Optional proto3 fields, introduced as an experimental feature in [3.12](https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0), are currently not supported. The following error is emitted when attempting to generate type stubs for a proto3 file with optional fields:

> is a proto3 file that contains optional fields, but code generator protoc-gen-mypy hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.

I might have a go at this myself if I get the time. Going by https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md it looks like it will mostly require some changes to `write_stringly_typed_fields`?

**Comment by nipunn1313** [comment]
Sorry for the delay - somehow missed this message and it got lost.

From the docs, it looks like you have to set
```
If you are generating code using raw CodeGeneratorRequest and CodeGeneratorResponse messages from plugin.proto, the change will be very similar:

void GenerateResponse() {
  CodeGeneratorResponse response;
  response.set_supported_features(CodeGeneratorResponse::FEATURE_PROTO3_OPTIONAL);

  // Generate code...
```

We'll want to add some tests to take advantage of this new feature - to make sure we're emitting reasonable types! (see test_generated_mypy.py). I suspect we'll want to emit Optional[x] instead of [x] for the field type  (it might be doing that anyhow - I don't recall offhand)

**Comment by henribru** [comment]
Yep, I had a go at it and have a (seemingly) working implementation. It's not super well tested but I'll improve that aspect. Looks like I'll also have to update `CodeGeneratorResponse` in typeshed, so I'll try to get that done first then submit a PR here, hopefully in the next two weeks.
