### ISSUE TITLE
Release mypy-protobuf 1.24

### ISSUE THREAD

**Issue by wisepotato** [dropbox/mypy-protobuf#170]
Hi, i'm currently using this package, and would really appreciate a release, i dont know how stable it is right now, but I'm mostly waiting on the optional support. Currently i have no types because of it... 

great package, thanks for maintaining.

**Comment by nipunn1313** [comment]
Hiya. Thanks for the interest.

Release is currently blocked on a new version of mypy being released - as the candidate 1.24 release requires information from typeshed. Unfortunately, mypy releases have been really slow in 2020, and there hasn't been a typeshed bump since May. There have been a variety of challenges over the course of the year. I've been in touch with the Mypy team (they're also at dropbox) - and it's actually looking quite close, which is exciting. Hopefully we can start off the new year with a release.

As soon as mypy 0.800 releases, I'll release v1.24 of mypy-protobuf.

In the meantime, you can use this via 

```
pip install git+https://github.com/dropbox/mypy-protobuf.git@master#subdirectory=python
```
Though you will similarly need to use an unreleased version of mypy for things to work.

**Comment by wisepotato** [comment]
thanks for the background information, good to see there's a company supporting mypy/ this package as well.

**Comment by wisepotato** [comment]
i'll try out your suggestion :)

**Comment by wisepotato** [comment]
It worked, thanks! still hoping for an official release ;)

**Comment by nipunn1313** [comment]
Released!

**Comment by nipunn1313** [comment]
https://pypi.org/project/mypy-protobuf/1.24
