### ISSUE TITLE
Cleaner documentation for gRPC docs protoc usage

### ISSUE THREAD

**Issue by giacomomagini** [dropbox/mypy-protobuf#172]
The official gRPC docs for python doesn't run `protoc` as command but it uses the python module (https://grpc.io/docs/languages/python/quickstart/#generate-grpc-code).
Can you please add an example on the documentation for this scenario? It took me a while to make it work with these options `--plugin=mypy_protobuf --mypy_out=<path>`.
Thanks 😄

**Comment by nipunn1313** [comment]
Hiya! Should work with just `--mypy_out=<path>` if you have mypy_protobuf installed - since it should put protoc-gen-mypy on your path. I believe we have such an example with protoc.

I'm unfamiliar w/ how GRPC invokes protoc - but it seems like the arguments are the same as the protoc invocation.
Perhaps someone who has gotten everything up and running w/ the GRPC flow would be excited about documenting getting started with GRPC?

I know a contributor worked on #133 and I'm looking into merging it soon (waiting for a mypy release)
Perhaps a separate md file w/ e2e instructions for grpc would be valuable.

**Comment by nipunn1313** [comment]
There should be instructions in the README now
