### ISSUE TITLE
Cyclical reference prevents generated code from being used with pyright

### ISSUE THREAD

**Issue by erictraut** [dropbox/mypy-protobuf#214]
Recent versions of mypy-protobuf generate code that includes a cyclical reference that prevents the code from being used with [pyright](https://github.com/microsoft/pyright).

The problem can be seen here:
```python
class Colors(metaclass= _Colors):
    V = NewType('V', int)

class _Colors(_EnumTypeWrapper[Colors.V], type):
    RED = Colors.V(0)
    GREEN = Colors.V(1)
    BLUE = Colors.V(2)
```

The generated code is using `_Colors` as a metaclass for `Colors`, but it's using `Colors` in the base class definition for `_Colors`. The type evaluation for the expression `Colors.V` depends potentially on metaclass behavior, but the metaclass can't be defined without accessing `Colors.V`. It's a cyclical dependency, and I don't see any way to break it.

I'm not sure why mypy is OK with this construct. I'm guessing that it happens to work because mypy is a multi-pass analyzer and silently gives up after n passes of trying to resolve this dependency? Or it simply fails to detect that there is a dependent cycle and proceeds as though everything is OK? Pyright is a lazy evaluator, so it can deal with dependencies in any order, but it cannot break a hard dependency like this, and I don't see a way to make it work, even in theory.

Do you have any thoughts or advice? Is there another way you could accomplish this without generating a cyclical dependency?

For example, could you define the type for `V` outside of the namespace of the class, like this? This appears to work fine with both mypy and pyright.

```python
from typing import Generic, NewType, TypeVar

T = TypeVar("T")

class _EnumTypeWrapper(Generic[T]): ...

_Colors_V = NewType("_Colors_V", int)

class Colors(metaclass=_Colors):
    V = _Colors_V

class _Colors(_EnumTypeWrapper[_Colors_V], type):
    RED = Colors.V(0)
    GREEN = Colors.V(1)
    BLUE = Colors.V(2)
```

**Comment by nipunn1313** [comment]
I think this was solved by #211 - which will release in the next release

**Comment by nipunn1313** [comment]
Credit to @MHDante

**Comment by nipunn1313** [comment]
it appears that @MHDante filed it with pywright prior to fixing it here themself!

**Comment by MHDante** [comment]
This was not solved by #211 ! That solved a different issue. 

I started looking into pyright after running into the cyclical dependency. Please reopen the issue!

> However, there is still the unknown type in the generic EnumTypeWrapper. I think I will investigate that in the pyright repo (since I assume it works with mypy)

**Comment by nipunn1313** [comment]
Thanks for the clarification

**Comment by nipunn1313** [comment]
Let me reach out to some folks from Mypy for advice here. This seems tricky.

**Comment by nipunn1313** [comment]
The downside to defining `_Colors_V` outside of the class are
- pollutes the outer namespace (V is something we want to scope within Colors)
- Mypy errors would suggest `_Colors_V` rather than suggesting `Colors.V`
Not to rule out the possibility, but to illustrate the downsides


I'm not sure about exactly why mypy is ok with this construct, or what alternative makes the most sense.

**Comment by nipunn1313** [comment]
Hi,

I want to preface by saying that I don't deeply understand how compilers/parsers/analyzers work very well. I took a class on it once a decade ago, but haven't touched it since, but can learn about it. I'll try to illustrate my understanding in my explanation so it can be double checked.

I chatted w/ folks from mypy. My understanding is that in the typing world, forward references and circular/recursive/corecursive types are very common (eg linked lists, ASTs etc). They mentioned that
the code above is valid for mypy - because mypy accepts circular-dependencies for this reason.

It does sound like the lines setting the fields may be of concern

I have a couple ideas here that may help.
- Eliminate field setting in the .pyi - since it should only show types
- Move fields to the "instance" Colors rather than the EnumTypeWrapper metaclass

Would either of these work? I would be willing to make either of these changes, with
slight preference to the first one.

```
class _Colors(_EnumTypeWrapper[Colors.V], type):
    pass

class Colors(metaclass= _Colors):
    V = NewType('V', int)
    RED: Colors.V  # 0
    GREEN: Colors.V  # 1
    BLUE: Colors.V  # 2
```

or

```
class _Colors(_EnumTypeWrapper[Colors.V], type):
    RED: Colors.V  # 0
    GREEN: Colors.V  # 1
    BLUE: Colors.V  # 2

class Colors(metaclass= _Colors):
    V = NewType('V', int)
```


There is still a circular dependency, but it would be in types rather than the RHS.
I don't think we can eliminate the circular typing - but hopefully co-recursive types can be supported by pyright.

Perhaps `from future import annotations` is relevant https://mypy.readthedocs.io/en/stable/runtime_troubles.html?highlight=future%20annotations  - though I believe mypy always behaves as if this is set (it must).

**Comment by erictraut** [comment]
Pyright supports forward references and even circular references when they can be resolved. The problem here is that a metaclass can influence which attributes appear within a class and the type of these attributes. 

Here's an example of where the attribute `x` takes on different types depending on the metaclass used:
```python
from enum import EnumMeta

class A:
    x = 0

class B(metaclass=EnumMeta):
    x = 0

reveal_type(A.x)  # int
reveal_type(B.x)  # Literal[B.x]
```

That means a type checker cannot understand what type is meant by the expression `Colors.V` prior to resolving the metaclass for `Colors` But resolving the metaclass for `Colors` requires resolving the class `_Colors`, and that requires resolving the type of `Colors.V`. I don't see any way to resolve that cycle.

Mypy does detect and report a similar class of cyclical dependency as an error. Here's an example:
```python
class C(D): ...
class D(metaclass=C): ...
```

Unfortunately, neither of your proposals above remedies the cyclical dependency.

I understand your point about polluting the outer namespace, but aren't you already introducing new names into the outer namespace, such as `_Colors`? If so, then it seems to me that it doesn't make the problem any worse if you were to introduce `_Colors_V`.

**Comment by nipunn1313** [comment]
Thanks for the explanation. That's helpful.
I walk back the point about polluting the outer namespace - it is true we do this already in mypy-protobuf, and it may be reasonable to do so in more places.

To provide context, the main concern I have been thinking about regards the potential error message confusion, which I was conflating w/ the namespace pollution. Thanks for clarifying.

Currently, `Colors` and `Colors.V` are a point of confusion (due to how protobuf's default python plugin makes a distinction between EnumTypeWrapper and the `int` in contrast to python's built in enum).

Currently, if a user does a line like
```
x: Colors = Colors.RED
```
it errors with
```
main.py:14: error: Incompatible types in assignment (expression has type "V", variable has type "Colors")
```
encouraging the user to discover and use `Colors.V`. Ideally it would say `expression has type "Colors.V"`, but this is pretty good.

In the past (version 1.*) of mypy-protobuf, we used to generate a top level value `ColorsValue`, comparable to the suggested `_Colors_V`. One of the main confusions was how it would generate this error instead:
```
main.py:15: error: Incompatible types in assignment (expression has type "_Colors_V", variable has type "Colors")
```
This might encourage the user to do `from colors_pb2 import _Colors_V` for typing rather than `Colors.V`. This encouraged usage won't work at runtime and would have to be hidden behind a TYPE_CHECKING import, and quoted in for the mypy typechecker. Hence the motion to move toward `Colors.V` strategy in the 2.* mypy-protobuf releases.


Poking a bit with mypy-playground, it does appear that this does seem to resolve in mypy, meaning that full resolution of `C` is not required by mypy.
```python
class C(D, type): ...
class D(metaclass=C): ...
```
What is expected to happen when resolving something like `D.x`? To my understanding, mypy is able to resolve both C/D, and then when trying to resolve `D.x` it can walk up the MRO while avoiding recursively walking back to D. Fully resolving C does not appear to be a prereq to resolving `D.x`

As a side note, it does appear that EnumMeta is special cased based to literal by mypy on https://mypy.readthedocs.io/en/stable/metaclasses.html - and some sourcediving into mypy, though I don't think that's relevant.

**Comment by erictraut** [comment]
Perhaps one of the contributors from mypy could respond directly to this thread. I consider it a bug in mypy that this cyclical dependency doesn't generate an error. It happens to work in this case because the metaclass doesn't affect the way in which the class member's type is evaluated, but in general it's unsafe to evaluate the type of a class member for a class before the metaclass type is not understood.

I can make this work in pyright by ignoring the cyclical dependency for metaclasses, but it would require me to introduce a bug that will likely come to bite us down the road. I'm reluctant to do this to work around a bug in the code that mypy-protobuf generates.

I understand your point about the error message leading users to do the wrong thing. I would think that most users would not attempt to import a symbol that begins with an underscore since that means it's private to the module, but not all Python developers are familiar with that naming convention.

I don't have any better ideas for avoiding the cyclical dependency other than the one I mentioned at the top of the this thread.

**Comment by nipunn1313** [comment]
Chatted with @JukkaL offline, but will summarize here - he can chime in if anything is missing.

Actual code would not be able to function if there was a true circular dependency, but in the world of typing it's different.
With metaclass typing code, it's a bit of a gray area where it can be useful to allow this sort of thing for practical benefit.

The actual generated protobuf code looks more like this
```python
Colors = EnumTypeWrapper()
```
`_Colors` is a mypy-protobuf construct to wrap EnumTypeWrapper with stronger typing for values. Colors at runtime is an instance of EnumTypeWrapper. We represent it as a class with a metaclass so that we can represent `Colors.V` as a type.

Here we've constructed a case where mypy allows something that pyright doesn't, but I don't think we've constructed a case where mypy yells when it shouldn't - dropping this into gray area of how a typing system should handle this (eg mypy resolves field `V` via MRO, meaning it doesn't need to figure out `_EnumTypeWrapper[V]` to resolve `Colors.V`).

That being said, independently, it seems reasonable to try and define this in a more direct way - it seems like Eric's idea is promising, though with the usability downside of suggesting _Colors_V rather than V. Jukka alluded to a future possibility of giving better error messages in alias situations (Eg `expected Colors.V - alias of _Colors_V`). Perhaps we can make it somewhat self explanatory to the sourcediver with something like
```
_Colors_V = NewType('_Colors_V', int)  # Can be referenced as Colors.V
```

**Comment by erictraut** [comment]
I still maintain that a type checker needs to figure out `_EnumTypeWrapper[V]` before it can correctly determine the type of the expression `Colors.V`. In Python, expressions of the form `class.attribute` may be affected by custom metaclass behavior. If the type of the metaclass is not known, then it's also not known whether to use a custom behavior. Mypy appears to be making the assumption in this case that the metaclass will not affect the answer, and this assumption happens to hold true in this particular case.

Here's an (admittedly contrived) example to consider:
```python
from typing import Generic, NewType, Type, TypeVar

T = TypeVar("T")

class A(metaclass=AMeta): ...

class AMeta(MetaBase[A.V], type):
    pass

class MetaBase(Generic[T]):
    def __getattribute__(self, name: str) -> Type[int]: ...

reveal_type(A.V)
```

Mypy emits an error in this case (`error: Name 'A.V' is not defined`), but it's a confusing error message because `A.V` is a valid expression that can be evaluated. It's just not resolvable at that point because it's part of a circular dependency. Mypy is able to determine the proper type of `A.V` when the expression is used outside of the circular dependency (`note: Revealed type is 'Type[builtins.int]'`).

I maintain that if mypy were to add a proper circular dependency check and emit a clear error message when that condition is detected, the code generated by mypy-protobuf would generate errors.

Maybe I'm worrying too much about an edge case that is unlikely to arise in practice. I could eliminate the circular dependency check in pyright and make the assumption that it will work correctly most of the time and produce confusing error messages when that assumption fails, but I don't feel good about that solution.

**Comment by JukkaL** [comment]
This seems like a rare edge case, though I can see that there is some buggy mypy behavior. To be honest, we have some much more serious open issues, so it's unlikely that this would get fixed in the near term by the core team, but feel free to create a mypy issue about.

**Comment by nipunn1313** [comment]
I'm flipping back and forth between sticking to generated code as written
```python
class Colors(metaclass= _Colors):
    V = NewType('V', int)

class _Colors(_EnumTypeWrapper[Colors.V], type):
    RED = Colors.V(0)
    GREEN = Colors.V(1)
    BLUE = Colors.V(2)
```

and

```python
from typing import Generic, NewType, TypeVar

T = TypeVar("T")

class _EnumTypeWrapper(Generic[T]): ...

_Colors_V = NewType("_Colors_V", int)

class Colors(metaclass=_Colors):
    V = _Colors_V

class _Colors(_EnumTypeWrapper[_Colors_V], type):
    RED = Colors.V(0)
    GREEN = Colors.V(1)
    BLUE = Colors.V(2)
```

The existing behavior appears to be buggy - in that it uses a circular dependency to trick typecheckers into scoping `V` inside `Colors.V`.

However, the existing behavior has the (rather large) benefit of suggesting `Colors.V` on error instead of `_Colors_V`. Protobuf's generated output is very confusing - and large number of people typing generated enums type them as `x: Colors = Colors.RED` - and it is really beneficial to have some way for the error message to direct folks toward `Colors.V`.

I don't have a strong philosophical stance here, but practically speaking, switching this will result in confusion.
I do wonder if there's some way to reach for best of both worlds.

```python
from typing import Generic, NewType, TypeVar

T = TypeVar("T")

class _EnumTypeWrapper(Generic[T]): ...

class _Colors(_EnumTypeWrapper[_Colors_V], type):
    V = NewType("V", int)  # Can be referenced as Colors.V
    RED = Colors.V(0)
    GREEN = Colors.V(1)
    BLUE = Colors.V(2)

Colors: _Colors

x: Colors.V = Colors.RED
reveal_type(Colors.V)
```

Something like this would be great (and more accurate), but `Colors.V` is not usable as a type here w/o the metaclass
```
main.py:12: error: Name 'Colors.V' is not defined
main.py:13: note: Revealed type is 'def (item: builtins.int) -> main._Colors.V'
```

I think I'm leaning toward the practical benefits of the existing impl.

Do you have some kind of type-ignore comment for pyright? I could autogenerate something like that to identify that mypy-protobuf is using a not-generalizably-usable circular reference. Eg `# type: ignore=circular_reference` on the line of the circular reference.

**Comment by erictraut** [comment]
Thanks for giving this some consideration. I know you're busy with other priorities.

I've also been wracking my brains trying to come up with a better suggestion that eliminates the cyclical dependency _and_ avoids the error message in mypy that is resulting in confusion.

Here's a potential solution. It has the downside that it requires some code duplication — namely overriding the four methods in `_EnumTypeWrapper` that require specialization.

```python
class Colors(_EnumTypeWrapper[Any]):
    V = NewType("V", int)
    RED = Colors.V(0)
    GREEN = Colors.V(1)
    BLUE = Colors.V(2)

    def Name(self, number: V) -> str: ...
    def Value(self, name: Union[str, bytes]) -> V: ...
    def values(self) -> List[V]: ...
    def items(self) -> List[Tuple[str, V]]: ...
```

Normally I'd be against code duplication like this because it makes the code difficult to maintain, but in code that is programmatically generated, this isn't so much of a problem. What do you think?

Another variation of this is to eliminate the use of `_EnumTypeWrapper` entirely.

```python
class Colors:
    V = NewType("V", int)
    RED = Colors.V(0)
    GREEN = Colors.V(1)
    BLUE = Colors.V(2)

    DESCRIPTOR: EnumDescriptor
    def __init__(self, enum_type: EnumDescriptor) -> None: ...
    def Name(self, number: V) -> str: ...
    def Value(self, name: Union[str, bytes]) -> V: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[V]: ...
    def items(self) -> List[Tuple[str, V]]: ...
```

If these variants don't work for you, Pyright does support the PEP 484 standard `# type: ignore` comment, so that's another option, but it's not a very satisfying one. It would need to look like this:

```python
class _Colors2(_EnumTypeWrapper[Colors2.V], type): # type:ignore
    RED = Colors2.V(0)
    ...
```

**Comment by nipunn1313** [comment]
is there something more specific like `#type: ignore=circular_import` that we could use to suppress the very particular error we're seeing? That would be the "tell the typechecker that we're specifically promising that the circular import is not an issue in this case".

overriding the specialized methods does actually seem promising as an option as well - as long as protobuf doesn't change the set of methods on enums in the enumtypewrapper very often.

One eventual dream of mine is to integrate this plugin into the generated code from google - so perhaps one day we'll have better options available to us.

If there's a way to ignore the specific error we know we're causing - I'd lean that way to minimize churn from changes to enumtypewrapper in the future. Otherwise, probably would lean toward the intentional overriding of the methods w/ more specific covariant types for the methods (per your suggestion).

**Comment by erictraut** [comment]
We support only the standard version defined in PEP 484. You can include "=<whatever>" afterward, but pyright will ignore the extra characters and treat it like a normal `# type: ignore`. Even if we were to add support for specific error classes in `# type: ignore` comments, those error class strings would be pyright specific. I wouldn't recommend generating code that is type-checker specific.

**Comment by nipunn1313** [comment]
At least currently (due to how the CI testsuite works) - this library is fairly mypy-specific, but I'll try and do my best to accommodate pyright as well since it's another popular typechecker. I'm all about the practicality.

**Comment by nipunn1313** [comment]
I've looped back to working on this.

I'm unhappy with the redundant-enumtypewrapper-method solutions, because there will be redundant code in typeshed and mypy-protobuf (likely to go out of date).

I was able to get the unsavory `# type: ignore` method working

I've tried this method:
```
_OuterEnum_V = typing.NewType('OuterEnum.V', builtins.int)
class OuterEnum(metaclass=_OuterEnum):
    V = _OuterEnum_V
x: _OuterEnum_V = _OuterEnum_V(5)
y: OuterEnum.V = OuterEnum.V(5)
```
pyright is happy with this, but I find that mypy is unhappy with
```
test/generated/testproto/test_pb2.pyi:28: error: Variable "testproto.test_pb2.OuterEnum.V" is not valid as a type
test/generated/testproto/test_pb2.pyi:28: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
```
Seems like potentially a mypy bug here (submitted https://github.com/python/mypy/issues/10788)
Probably this final strategy is closer to what we want, but requires some bugfixes first. Will go with the type-ignore strat as a bandaid for now.

**Comment by nipunn1313** [comment]
> (It occurs to me that the current generated code will run into problems if the user-defined enum member names conflict with "DESCRIPTOR", "Name", "Value", etc. Have you run into this issue?)

I just wrote some tests to see what happens with this.

For name conflict with `DESCRIPTOR` protobuf generates invalid / broken code (fails at import time - since DESCRIPTOR gets overwritten as an int)
```
>>> from testproto.test_pb2 import OuterEnum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nipunn/src/mypy-protobuf/test/generated/testproto/test_pb2.py", line 854, in <module>
    DESCRIPTOR.message_types_by_name['Simple1'] = _SIMPLE1
AttributeError: 'int' object has no attribute 'message_types_by_name'
```
Filed https://github.com/protocolbuffers/protobuf/issues/8803

For `Name` and `Value` naming conflicts, it's not so bad. protobuf generates working code. You can still access `Name`, but not via `OuterEnum.Name`. `OuterEnum.Name` prefers the method over the enum variant value.
```
>>> from testproto.test_pb2 import OuterEnum
>>> from testproto.test_pb2 import OuterEnum, Name
>>> OuterEnum.Value('Name')
4
>>> Name
4
```

mypy-protobuf generates broken stubs here, which we could fix. Filed #238 for those.

**Comment by nipunn1313** [comment]
#237 should fix this w/ bandaid

Opening #239 for follow up and #238 for the other issue that came up in this thread

**Comment by MHDante** [comment]
Thank you for your hard work on this. We are using `#type: ignore` internally and its ok at the moment, but we lose safety on enum operations. 

I look forward to upstream response on this

**Comment by nipunn1313** [comment]
With mypy-protobuf 2.6, you shouldn't need `# type: ignore` any longer in your own code for enums (since the generated code will have it instead after #237). Let me know if you're seeing further issues. Also filed #241 - for adding pyright to CI.

**Comment by nipunn1313** [comment]
I managed to find a satisfactory solution in #260.
```python
class MyEnum(_MyEnum, metaclass=_MyEnumEnumTypeWrapper):
    pass
class _MyEnum:
    V = typing.NewType('V', builtins.int)
class _MyEnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MyEnum.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    FOO = MyEnum.V(0)
    BAR = MyEnum.V(1)
FOO = MyEnum.V(0)
BAR = MyEnum.V(1)
```

This pulls out the `V` into a separate class.
The `MyEnumEnumTypeWrapper` metaclass depends on `V`. The "instance" of `MyEnum` is implemented using a metaclass as well as multiple inheritance so that `MyEnum.V` is a valid type - with no circular dependencies!

The mypy errors given are of the form
```
test_negative/negative.py: error: Argument 1 to "Name" of "_EnumTypeWrapper" has incompatible type "testproto.test3_pb2.SimpleProto3._InnerEnum.V"; expected "testproto.test3_pb2._OuterEnum.V"
```
Which is marginally better than something like `_InnerEnum_V` (which would require python/mypy#10788 anyway)
I'm pretty happy with this solution at the intersection of practicality and correctnes
