### ISSUE TITLE
Windows + VSCode + vscode-proto3: unable to find protoc-gen-mypy unless .exe extension is specified in .bat script

### ISSUE THREAD

**Issue by Gliptal** [dropbox/mypy-protobuf#215]
When using [vscode-proto3](https://github.com/zxh0/vscode-proto3) on VSCode:

````
"protoc": {
            "path": "C:\\Portable\\Protobuf\\protoc.exe",
            "compile_on_save": true,
            "options": [
                "--plugin=protoc-gen-mypy=${workspaceRoot}/.venv/Scripts/protoc_gen_mypy.bat",
                "--proto_path=${workspaceRoot}/src/module/network/proto",
                "--python_out=${workspaceRoot}/src/module/network/proto",
                "--mypy_out=${workspaceRoot}/src/module/network/proto"
            ]
        }
````

`protoc` throws an error aboiut being unable to find `protoc-gen-mypy`:

![Code_q7ZJZJRXrb](https://user-images.githubusercontent.com/3907646/112614360-769d0900-8e21-11eb-9fc1-ebf57bb480d3.png)

This can be easily solved by adding `.exe` to the `.bat` script:

````
@echo off
%~dp0\python -u %0\..\protoc-gen-mypy.exe
````

Am I missing something in the setup or `protoc`'s commandline parameters?

**Comment by nipunn1313** [comment]
haven't tested explicitly on windows in quite a while - it used to reference `protoc-gen-mypy` as a sibling - it is possible that https://github.com/dropbox/mypy-protobuf/commit/034f0f0063dd1166f71327ddd90857f0d952cabc may have changed the way this works.

It would be awesome if we were able to add internal tests to really verify things work on windows.
If you can confirm that it installs to `protoc-gen-mypy.exe` rather than `protoc-gen-mypy` on windows, then happy to accept such a diff!

Am curious whether you could directly pass
```
--plugin=protoc-gen-mypy=${workspaceRoot}/.venv/Scripts/protoc_gen_mypy.exe
```

If that's the case, then perhaps we can drop the `.bat` file entirely.

**Comment by nipunn1313** [comment]
We used to have the bat file prior to #102  - since the original file was not executable. The console entrypoints may obviate the need for the batch file.

Thanks for the report!
