### ISSUE TITLE
WhichOneOf return value should be Optional

### ISSUE THREAD

**Issue by wmdrichards** [dropbox/mypy-protobuf#218]
Currently mypy-protobuf marks `WhichOneof` as returning a Literal containing only the string names of the fields under the oneof. It should also include `None`, which is returned by `WhichOneof` when none of the fields inside the oneof are populated

**Comment by nipunn1313** [comment]
great find! Thanks for the report. This should allow for better typing - avoiding bugs where the dev does not consider the unpopulated case.

There may be new errors reported with the new version of mypy-protobuf with the fix - since previously the return type would match str, but now it won't (will match Optional[str], or will require an `assert x is not None`).
