### ISSUE TITLE
Bake version in code during builds

### ISSUE THREAD

**Issue by tarmath** [dropbox/mypy-protobuf#220]
Hello!

When we compile protobufs with protoc, we also generate a version.py file at the top level of each packages. This file currently contains both the package's version being compiled, and the protoc version used for compiling. 

I'd like to do the same with mypy-protobuf and record its version as well.

Essentially, this file would look like this:

    __version__ = "1.2.3"
    __protoc_version__ = "3.17.1"
    __mypy_protobuf_version__ = "2.5"

However right now mypy-protobuf does not expose its version anywhere, so it would be great if it could be added!

**Comment by nipunn1313** [comment]
It sounds like you’d like the generated code to include a version number
for mypy protobuf? For what purpose were you envisioning?

That sounds useful for someone manually inspecting the code to know what
generated it.

Is there a precedent that protoc automatically creates? What generates the
version.py you’re referencing?

Currently mypy protobuf only creates .pyi files with a header comment. We
could update the header comment to include the version number as an easy
first pass to this idea.

—Nipunn

**Comment by tarmath** [comment]
Im having to deal with multiple packages that include compiled protobufs with stubs that were generated with different versions of mypy-protobuf inside a single project, and given the recent breaking changes, I'd like to have this kind of meta information available in these packages to more easily pinpoint the culprit(s) going forward. 

It's also generally considered good practice to keep track of these things. Doing so for the protoc version has helped us quite a few times in the past actually!

As an example, google's protoc executable exposes its version like so:

    > protoc --version
    libprotoc 3.14.0

It would be ideal if protoc-gen-mypy could achieve the same...

**Comment by tarmath** [comment]
Here is how it's managed with protobuf itself:

https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/__init__.py#L33

https://github.com/protocolbuffers/protobuf/blob/master/python/setup.py#L39-L48

If you wouldn't mind managing the version from the code directly moving forward, and then reading that in setup.py instead, it becomes very straightforward to add support for it in your module...

**Comment by nipunn1313** [comment]
I see. Thanks for the clarification. Appreciate the code links - all seems like stuff we could support here.
I am not fully sure I understand the request - so I want to make sure we're on the same page.

You have mentioned a couple of suggested changes

1) for a command line version number accessibility - eg
```
> protoc-gen-mypy --version
2.5
```

2) version number being generated into the stub header
Eg. `.pyi` file with
```python
"""
@generated by mypy-protobuf 2.5.  Do not edit manually!
isort:skip_file
"""
```

Or even potentially
2b)
```python
"""
@generated by mypy-protobuf 2.5.  Do not edit manually!
isort:skip_file
"""
__mypy_protobuf_version__ = "2.5"
```


You mentioned dealing with multiple packages compiled with different versions of mypy-protobuf within the same project. It sounds like the command line version number wouldn't help with the problem you're facing - since you'd need it in the package. What are you hoping for mypy-protobuf to do here?


Also one question that might help give me some context

>  we also generate a version.py file at the top level of each packages

Who is "we" here? More specifically, are you affiliated with the protoc developers? Trying to understand if "version.py" is something standard with protoc, or something custom that you're trying to develop for your own specific project, or something else.

**Comment by tarmath** [comment]
Thanks for the quick responses!

Im only looking for 1) here really, as I already have in place everything else needed to add the version in a generated version.py that gets included in the package/distribution, along with the compiled protobufs and mypy-protobuf stubs.

I/we are not affiliated with protoc at all :)

My understanding is that the vast majority of python libraries/utilities expose their version through more convenient means than having to read their distribution information with importlib and the such. For libraries this happens generally with a __version__ property:

 * https://github.com/python-attrs/attrs/blob/main/src/attr/__init__.py#L25
 * https://github.com/tkem/cachetools/blob/master/src/cachetools/__init__.py#L24

(and so on)

... while for executables it is through a `-V` or `--version` argument
