### ISSUE TITLE
Using enum V type with Literal

### ISSUE THREAD

**Issue by bbatliner** [dropbox/mypy-protobuf#305]
I'm trying to use mypy-protobuf types in `Literal` types in combination with `@overload`, see example below:

```proto
# example.proto
syntax = "proto3";
enum Example {
    FOO = 0;
    BAR = 1;
    BAZ = 2;
}
```

```python
# example.py
@overload
def process_enum(e: Literal[example_pb2.FOO]) -> bool: ...
@overload
def process_enum(e: Literal[example_pb2.BAR]) -> str: ...
@overload
def process_enum(e: Literal[example_pb2.BAZ]) -> int: ...
def process_enum(e: example_pb2.Example) -> Union[bool, str, int]: ...
```

I'm using `mypy-protobuf` 3.0.0.

Because the mypy-protobuf is wrapped in a `NewType`, mypy doesn't accept using it in `Literal`, which seems like a deficiency in mypy given that the `NewType` transparently maps to an `int` value. This is probably because "`Literal` may be parameterized with literal ints, byte and unicode strings, bools, Enum values and None" per [PEP 586](https://www.python.org/dev/peps/pep-0586/), which unfortunately doesn't include `NewType`.

For sake of comparison, this works with vanilla Enums:

```python
class Example(Enum):
    FOO = 0
    BAR = 1
    BAZ = 2

@overload
def process_enum(e: Literal[Example.FOO]) -> bool: ...
@overload
def process_enum(e: Literal[Example.BAR]) -> str: ...
@overload
def process_enum(e: Literal[Example.BAZ]) -> int: ...
def process_enum(e: Example) -> Union[bool, str, int]: ...
```

Would the resolution of #169 resolve this by replacing the `NewType` with a mere type alias to `int`?

**Comment by nipunn1313** [comment]
I think `Literal` is intended, spec'd and implemented to be pretty simple.
```
Literal[5]  # ok
X = 5
Literal[X]  # not ok
```

Extending to NewType would make
```
NT = NewType("NT", int)
Literal[NT(5)]  # ok
X = NT(5)
Literal[X]  # still not ok
```

In addition to extending to NewType, it would need to extend to constant variables like X - not just literals. I think it becomes a can of worms, because there's nothing that actually enforces that the variables are constant in python. To be fair, enum values already delve slightly into this can of worms (with `Example.FOO` in your case), so maybe it's ok to suggest that extension of Literal capabilities. I think you'd have to suggest it either as a PR to PEP586 or possibly a discussion issue in the mypy repo. There might be factors I'm not considering.

I think we want to keep mypy-protobuf honest to what protoc's python code does. If we type `Example` as an `Enum` - it incorrectly implies to the type system that it has access to all the powers of `Enum` - which I think is not worth the benefit here unfortunately.

**Comment by bbatliner** [comment]
Thanks for the discussion. I'll ponder if there's anything to bring up with mypy or PEP586. Closing this issue as there's nothing for mypy-protobuf to do here.
