### ISSUE TITLE
Double quotes in protobuf comments not handled correctly in generated docstring

### ISSUE THREAD

**Issue by vvasavada-fn** [dropbox/mypy-protobuf#313]
I have a protobuf with a field that looks like this:

`string name = 1;  // The name of the field, for example "blah"`

When I generate the `pyi`, I get a docstring that looks like: 

`"""The name of the field, for example "blah""""`

which causes a syntax error due to the four double quotes. I recently updated to `mypy-protobuf==2.10` and I think this is an issue with changes from https://github.com/dropbox/mypy-protobuf/pull/298. Please let me know if there is any other info I can provide! Thanks!

**Comment by nipunn1313** [comment]
Hiya! I don't believe #298 is the issue like you mentioned. That one isn't in release 2.10

The issue you described was introduced in 2.10 (#281) and it is fixed in 3.0.0 (#297)

There are tests for it here https://github.com/dropbox/mypy-protobuf/blob/main/proto/testproto/comment_special_chars.proto#L5

Check
https://github.com/dropbox/mypy-protobuf/blob/main/CHANGELOG.md#300

Are you able to update to 3.0.0? I realize 3.0.0 comes with some other stuff (dropping targeting py2.7)

I could make a 2.10.1 which cherry-picks the particular fix for escaping - but if 3.0.0 works for you, that's even better.

**Comment by vvasavada-fn** [comment]
Ah I updated to 3.0.0 and that fixed this! Thanks!!
