### ISSUE TITLE
Plugin does not generate gRPC stubs to *_pb2_grpc.py

### ISSUE THREAD

**Issue by vmagamedov** [dropbox/mypy-protobuf#46]
Starting from some version of the protoc compiler, gRPC service stubs are no longer generated into `*_pb2.py` files. Now they are generated into separate `*_pb2_grpc.py` files. So to properly support grpcio library `*_pb2_grpc.pyi` files should be generated for service stubs.

And it would be great to generate gRPC stubs optionally, this would be possible if two separate CLI options (plugins) for protoc were created:
- `--mypy_out` for messages
- `--mypy_gprc_out` for gRPC stubs

I'm asking for this feature because I'm the author of the [grpclib](https://github.com/vmagamedov/grpclib) library, which is an alternative gRPC implementation for asyncio, and users of this library don't need gRPC stubs for grpcio.

**Comment by nipunn1313** [comment]
The plugin actually generates generic_services stubs (see here https://developers.google.com/protocol-buffers/docs/reference/python-generated#service)

mypy-protobuf currently hasn't been tested to work with GRPC stubs.

An additional flag `--mypy_grpc_out` sounds like a great feature.

**Comment by nipunn1313** [comment]
I think the work item here is to create a second plugin alongside `protoc-gen-mypy` that looks like `protoc-gen-mypy_grpc` which generates gRPC stubs.

Additionally, we should gate the generation of generic service stubs in *_pb2.py to only appear when `option py_generic_services = true;` is set

**Comment by vmagamedov** [comment]
Thank you for making service stub type hints generation optional. This totally suits me.

Wanted to note, that [protobuf](https://developers.google.com/protocol-buffers/docs/reference/python-generated#service) documentation also states that:
> If neither of the above lines are given, the option defaults to false, as generic services are **deprecated**. (Note that prior to 2.4.0, the option defaults to true)

So this is a deprecated feature. And I think that currently it is better to consult gRPC docs for gRPC-related work: https://grpc.io/docs/reference/python/generated-code.html, because all gRPC-related work moved into different projects and into plugins to generate appropriate stubs. And maybe this means that it is worthless to support `py_generic_services` option at all.

**Comment by nipunn1313** [comment]
To be clear, the existing support in mypy-protobuf is *not* for GRPC. It is for `py_generic_services` which is part of the regular `--python_out` plugin

We use `py_generic_services` at Dropbox for non-grpc transports, so we're definitely going to keep support for it for the time being. More broadly, I think having support for a recently deprecated option that's still used in the wild is reasonable.

Protoc recommends each RPC system built on proto (eg GRPC) to generate its own stubs rather than using a generic stub with a call method, 

`mypy-protobuf` currently does not support GRPC stub typing, but I would be happy to look at any PRs seeking to add support via an additional plugin (protoc-gen-mypy_grpc or something along those lines)! It sounds like a great idea.

**Comment by vmagamedov** [comment]
I'm sorry, I wasn't using protobufs so long and don't know that much about generic services and how they were used.

Do you prefer to close this issue or to leave opened to keep track of adding gRPC support in the future?

**Comment by nipunn1313** [comment]
Lets leave it open to track adding gRPC mypy-protobuf support
I think it should be fairly doable with a second plugin

**Comment by samuela** [comment]
I have a WIP version here: https://github.com/samuela/grpc-polyglot. You can get started with 

```
$ git clone https://github.com/samuela/grpc-polyglot.git
$ cd grpc-polyglot/python/
$ virtualenv --python=python3 venv
$ source venv/bin/activate
$ pip install -r requirements.txt
$ ./build_protos.sh
$ ./typecheck.sh
```

But it's still far from typechecking the gRPC bits appropriately.

**Comment by reorx** [comment]
@vmagamedov In an ideal world, `protoc --python_out` produces pyi so that we don't bother using mypy-protobuf, or even better if `_pb2.py` files has complete type hints, in which way pyi is not needed.

Now, because your grpclib doesn't use grpc stubs (`_pb2_grpc.py`), and it has its own protobuf plugin to generate the "grpclib stubs" (`_grpc.py`), I think what suits you most is to let your `protoc-gen-python_grpc` plugin generates pyi files, or just make the `_grpc.py` file has complete type hints for all the grpc service classes and methods.

Example for `_grpc.pyi` (`examples/helloworld/helloworld_grpc.pyi`):

```python
import grpclib.client
import helloworld.helloworld_pb2


class GreeterStub:
    def __init__(self, channel: grpclib.client.Channel) -> None: ...

    async def SayHello(self, req: helloworld.helloworld_pb2.HelloRequest) -> helloworld.helloworld_pb2.HelloReply: ...
```

Example for adding type hints to `_grpc.py` (`examples/helloworld/helloworld_grpc.py`), this one changes the generated code, makes `SayHello` a real method so that we can annotate it:

```python
class GreeterStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self._methods = {
            'SayHello': grpclib.client.UnaryUnaryMethod(
                channel,
                '/helloworld.Greeter/SayHello',
                helloworld.helloworld_pb2.HelloRequest,
                helloworld.helloworld_pb2.HelloReply,
            ),
        }

    async def SayHello(self, req: str) -> helloworld.helloworld_pb2.HelloReply:
        return await self._methods['SayHello'](req)
```

Both ways can achieve the goal of having nice typing stub classes (both are tested with mypy and python).

As to the original suggestion, I agree with @nipunn1313 that we can have a separated plugin like `protoc-gen-mypy_grpc` to handle it, but personally I would rather use grpclib as long as the typing support is completed :)

**Comment by vmagamedov** [comment]
@reorx Typing support in grpclib is already 100% completed. This issue was created mostly because I didn't knew about generic services existence. My issue was totally resolved in #47.

**Comment by reorx** [comment]
@vmagamedov oh, sorry if I misunderstood anything, but are you sure typing in grpclib generated files is also 100% completed? When I tried the helloworld example, typing information was not provided in [GreeterStub.SayHello](https://github.com/vmagamedov/grpclib/blob/master/examples/helloworld/helloworld_grpc.py#L32), and from the code I didn't see any annotation for the client stub methods, have I missed something?

**Comment by vmagamedov** [comment]
@reorx Take a look at the [UnaryUnaryMethod](https://github.com/vmagamedov/grpclib/blob/82a7c7f/grpclib/client.py#L717) implementation, it is annotated as a generic type with two type vars.

If you have any other questions about grpclib, please open an issue in the corresponding repository :) Don't want to generate noise for maintainers and users of this project.

**Comment by chadrik** [comment]
This project has been a life-saver so far even without grpc support, but I'd love to see this issue resolved!

**Comment by nipunn1313** [comment]
@Evgenus worked on a grpc-stubs implementation - which is now landed on master and will get into the next release
