### ISSUE TITLE
pycharm completions are broken

### ISSUE THREAD

**Issue by AlmogCohen** [dropbox/mypy-protobuf#60]
Generating [this file](https://github.com/tetration-exchange/pol-client-java/blob/master/proto/network_enforcement/tetration_network_policy.proto) with `protoc --python_out=. --mypy_out=. tetration_network_policy.proto` on python 3.7. Python 3.6 tested with same results.

The resulting file is full of `Unresolved reference 'TetrationNetworkPolicyProto'` errors and auto-completions does not work. You can check the screenshot here: 
![image](https://user-images.githubusercontent.com/3888998/51066087-28dbb380-15bd-11e9-8c48-426223ec6516.png)

When I simply delete all the `TetrationNetworkPolicyProto.` occurrences in the file, tada! All errors are gone and completions throughout the project work great. I'm not versed enough with the mechanics of python typing yet so I've had no insights for where the problem could be coming from.

**Comment by nipunn1313** [comment]
Thank you for the report! Looks like a real bug.

I believe that `mypy-protobuf` has a bug where if you have a capitalized package name (like `TetrationNetworkPolicyProto` or a lowercase message name, then `mypy-protobuf` generates incorrect code.

This is due to a rather unfortunate usage of `isUpper` in `protoc-gen-mypy` to determine the relative path.

We never came across this because we were primarily using this in go and python which have different standard casing models.

Working on a fix! Appreciate the report.

**Comment by AlmogCohen** [comment]
Thanks! I think that the Google ProtoBuf python interface is one of the
ugliest implementations I've seen in my life, yet your package make it
digestible and accessible. Thank you for the good work :)

**Comment by AlmogCohen** [comment]
You are awesome thanks!!! I'll give it a try soon but feel like it is
already fully tested :)

**Comment by cnpackard** [comment]
Hi @nipunn1313, thanks for fixing this issue! Does the mypy-protobuf team have any plans for when the fix will be released on PyPI?

**Comment by nipunn1313** [comment]
Ah that was an oversight on our part! Ill go ahead and kick a new version as soon as I can

**Comment by nipunn1313** [comment]
1.9 should be up on pypi now!

**Comment by cnpackard** [comment]
Pulled 1.9 and running smoothly with lowercased messages, thanks again!
