### ISSUE TITLE
Proposal: Enum Literals Support

### ISSUE THREAD

**Issue by nipunn1313** [dropbox/mypy-protobuf#84]
See Discussion in #56 

I actually think we're able to get best of both worlds here by using the mypy Literal type. This way, the typing will be indeed an int, but the int is constrained to only the legitimate values.

https://mypy.readthedocs.io/en/latest/literal_types.html

First attempt at a diff was #79 
Discussion after landing:

@Kami
> First thanks for adding enum literal support.
> 
> This indeed seems to fix direct enum literal notation, but it breaks the `Value()` method scenario which takes a string (enum name) and returns an enum value.
> 
> For example, with the following definition:
> 
> ```protobuf
> enum ExecutionStatus {
>     REQUESTED = 0;
>     SCHEDULED = 1;
>     RUNNING = 2;
> }
> ```
> 
> This used to work:
> 
> ```shell
> from messages_pb2 import ExecutionStatus
> 
> status_str = 'requested'
> obj.status = ExecutionStatus.Value(status_str.upper())  # this should return enum value (aka Enum type / int)
> ```
> 
> Now it returns the following error:
> 
> ```shell
> error: Incompatible return value type (got "Union[Literal[0], Literal[1], Literal[2]]", expected "ExecutionStatus")
> ```
> 
> It works fine with just the change from #81, but not with this change.
> 
> It may also brake `Name()` and other enum class methods, but I didn't have time to dig in yet.

@nipunn1313 
> I poked around a bit and I believe that the issue here is that `obj.status` is typed to `ExecutionStatus`, but it would now need to be typed to `ExecutionStatus.ClosedValueType`
> 
> since ExecutionStatus is the enum itself and `ExecutionStatus.ClosedValueType` is the type of the Values in the enum (and `ExecutionStatus.ClosedKeyType` is the type of the Keys in the enum)
> 
> The merged PR was non-backward-compatible in that it changed the return value of Typing to literals, and move the int-y-ness of the enum to the `ClosedValueType` member.
> 
> This is more accurate based on this example I found
> 
> ```
> enum UserFSWAction {
>    UNKNOWN = 0;
>    ALLOW = 1;
> }
> ```
> 
> ```
> >>> type(ALLOW)
> <class 'int'>
> >>> ALLOW
> 1
> >>> UserFSWAction.Name(1)
> 'ALLOW'
> >>> UserFSWAction.Value('ALLOW')
> 1
> >>> type(UserFSWAction.Value('ALLOW'))
> <class 'int'>
> ```
> 
> @Kami - does that make sense directionally?
> 
> I'll hold off on publishing to pypi until we have some alignment here. I'm ok with making a non-backward compatible change, but I'll want to have some clear changelist and bump the big version number.
> 
> Couple more considerations for proposal
> 
> change typing of the constants to be the ClosedValueType for better error messages
> 
> ```
> - ALLOW: typing_extensions___Literal[1]
> + ALLOW: UserFSWAction.ClosedValueType
> ```
> 
> change `ClosedValueType` to just `ValueType` to simplify notation required by callers.

**Comment by reorx** [comment]
For the past two weeks of using mypy-protobuf, I was always thinking about this issue and whether its good or not to use Literal for enum values, now I have some conclusions, it may not be the best or the most suitable (for your situation), but I hope it can provide some ideas to improve.

I'll illustrate my ideas by compare the assuming changes to the current code of `test_pb2.py:OuterEnum`:

```python
class OuterEnum(builtin___int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: builtin___int) -> builtin___str: ...
    @classmethod
    def Value(cls, name: builtin___str) -> 'OuterEnum': ...
    @classmethod
    def keys(cls) -> typing___List[builtin___str]: ...
    @classmethod
    def values(cls) -> typing___List['OuterEnum']: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[builtin___str, 'OuterEnum']]: ...
    FOO = typing___cast('OuterEnum', 1)
    BAR = typing___cast('OuterEnum', 2)
FOO = typing___cast('OuterEnum', 1)
BAR = typing___cast('OuterEnum', 2)
```

Firstly, I think `def Name` should accept any int value, not just restricted to the defined enum values. Assuming we are writing some code to convert int to enum name, the int may come from anywhere like json, database, user input etc, so it's possible to be an invalid enum value:

```python
def int_to_enum(i: int) -> Optional[str]:
    try:
        return OuterEnum.Name(i)
    except ValueError:
         return
```

looking at this code, `i` is totally arbitrary but as expected, if `def Name` is annotated as `Union[Literal[0], Literal[1], ...]`, it would be very weird and unnecessary. So I think using `Union[int, OuterEnum]` for `Name` is enough:

```diff
--- current.py	2019-08-06 21:28:13.000000000 +0800
+++ one.py	2019-08-06 21:22:50.000000000 +0800
@@ -1,7 +1,7 @@
-class OuterEnum(builtin___int):
+class OuterEnum:
     DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
     @classmethod
-    def Name(cls, value: builtin___int) -> builtin___str: ...
+    def Name(cls, value: Union[builtin___int, 'OuterEnum']) -> builtin___str: ...
     @classmethod
     def Value(cls, name: builtin___str) -> 'OuterEnum': ...
     @classmethod
```

Furthermore, I think the most important thing we want from pyi is the information and suggestions about **type**, not **value**, define all enum names and values in `Literal` is just too bloated, I can't see much benefits from it.

Secondly, we know the truths are, `OuterEnum` is an object of `EnumTypeWrapper`, and enum values are nothing but builtin `int` values, why not we just annotate enum exactly as the implementation of pb2 files, rather than pretend `OuterEnum` is a subtype of int? There may be historical reasons or special needs in Dropbox's code for that, but from my perspective the idea of just using int as enum value type will make the understanding much simpler, `Literal` is also not considered in this situation:

```diff
--- current.py	2019-08-06 21:28:13.000000000 +0800
+++ two.py	2019-08-06 21:29:03.000000000 +0800
@@ -1,16 +1,16 @@
-class OuterEnum(builtin___int):
+class OuterEnum:
     DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
     @classmethod
     def Name(cls, value: builtin___int) -> builtin___str: ...
     @classmethod
-    def Value(cls, name: builtin___str) -> 'OuterEnum': ...
+    def Value(cls, name: builtin___str) -> builtin___int: ...
     @classmethod
     def keys(cls) -> typing___List[builtin___str]: ...
     @classmethod
-    def values(cls) -> typing___List['OuterEnum']: ...
+    def values(cls) -> typing___List[builtin___int]: ...
     @classmethod
-    def items(cls) -> typing___List[typing___Tuple[builtin___str, 'OuterEnum']]: ...
-    FOO = typing___cast('OuterEnum', 1)
-    BAR = typing___cast('OuterEnum', 2)
-FOO = typing___cast('OuterEnum', 1)
-BAR = typing___cast('OuterEnum', 2)
+    def items(cls) -> typing___List[typing___Tuple[builtin___str, builtin___int]]: ...
+    FOO: builtin___int = 1
+    BAR: builtin___int = 2
+FOO: builtin___int = 1
+BAR: builtin___int = 2
```

That's it, what do you think?

**Comment by nipunn1313** [comment]
yep - that sounds reasonable - I think the typing as a subclass of int hasn't added value.

As for using `Literal`, see https://github.com/dropbox/mypy-protobuf/issues/56#issuecomment-445752916 for the motivation. Without a significantly compelling reason, it's simpler not to add `Literal` - but will leave this task open for discussion.

Removing the subclassing from int feels independently valuable based on this discussion.
Thanks!

**Comment by nipunn1313** [comment]
Closing issue now that we have an enum value type!
