### ISSUE TITLE
mypy raises error on .append on repeated field

### ISSUE THREAD

**Issue by gtalarico** [dropbox/mypy-protobuf#85]
### Proto
```proto
# rules.proto
message Result {
  string name = 1;
}

message ResultList {
  repeated Result results = 2;
}
```
### Code
```python
import rules_pb2
r = Results(name="x")
result_list = ResultList()
result_list.results.append(r)
# Append works as expected, mypy raises: 
# RepeatedCompositeFieldContainer[Results]" has no attribute "append" mypy(error)
```

### Mypy stub
```python
class Results(google___protobuf___message___Message):

    @property
    def results(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ResultList]: ...

```

**Comment by nipunn1313** [comment]
Hi! Thanks for reporting. This looks like a shortcoming of typeshed.

Typeshed's type for the `RepeatedCompositeFieldContainer` appears to be missing append and insert https://github.com/python/typeshed/blob/master/third_party/2and3/google/protobuf/internal/containers.pyi#L40

Append and insert exist in google's implementation here
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/internal/containers.py#L383
They appear to have been added recently (around 5 months ago) here
https://github.com/protocolbuffers/protobuf/commit/d8c2501b43c1b56e3efa74048a18f8ce06ba07fe

I believe the fix is to apply a PR to typeshed. I will work on putting one up.

**Comment by nipunn1313** [comment]
Once https://github.com/python/typeshed/pull/3136 lands you can update to the latest master of mypy for the fix. Alternately, you can wait for mypy to release (~1/month) and update to the latest.

**Comment by gtalarico** [comment]
Thank you so much for looking into this.
This project has been a big help

**Comment by nipunn1313** [comment]
Cool python/typeshed#3136 is in. Closing this out.

You'll have to wait until
1) Mypy pulls forward its pin of typeshed
2)Mypy cuts another release
2 - typically happens around monthly.

In the meantime, you can use ".add" instead of ".append" or do a `# type: ignore` on the line
